### ISSUE TITLE
Can't make the module for python 

### ISSUE THREAD

**Issue by Sinking-Stone** [SecretHQ/seal-cuda#1]
I am using Ubuntu20.04, python version is pytho3.11, I have installed nvcc, but when I run `bash makepackage.sh` I can't get the 'build/pytroy.cpython-311-x86_64-linux-gnu.so' file, how should I solve this problem?
![图片](https://github.com/SecretHQ/seal-cuda/assets/89176650/37f33f24-152c-4be0-9afe-f6c953a99def)
![图片](https://github.com/SecretHQ/seal-cuda/assets/89176650/47e8dd2f-e5da-49d4-8835-f444de18cfd0)

**Comment by gsxgoldenlegendary** [comment]
Maybe you have noticed that there are other errors which are "nvcc: 未找到命令" before where you said there were errors. I encountered the same situation. 

There are 2 solutions:

1. Add CUDA into **system** environmental variables, or
2. Read the shell code and executive each line one by one.

**Comment by Sinking-Stone** [comment]
thank you.
